### ISSUE TITLE
Phone format

### ISSUE THREAD

**Issue by batcapu** [M-Ulyanov/ng2-inputmask#1]
Hi,
When I put a US phone format mask such as (000) 000-0000 and I delete all the information a bracket stays there.
![image](https://cloud.githubusercontent.com/assets/28634061/25968120/5f5de72e-365e-11e7-99dc-fc388368c66c.png)
 
Here is my input 
```
<input type="text" id="orgPhone" class="form-control" mask="(000) 000-0000"
               required
               name="orgPhone" [(ngModel)]="contactForm.orgPhone" #orgPhone="ngModel">
```

Also, if you keep typing with any kind of masks it adds an extra character at the end.
![image](https://cloud.githubusercontent.com/assets/28634061/25968254/d79d4108-365e-11e7-8101-a3c20c0071e7.png)

**Comment by maxulyanov** [comment]
Hi it was fixed in the version 0.1.5
