### ISSUE TITLE
Text field with long size

### ISSUE THREAD

**Issue by jaxkodex** [M-Ulyanov/ng2-inputmask#3]
Hello, I am trying to set a mask to an input field of length of 100, i've read a little the code and kind of got that it validates length an regex from the mask value. So for 100 input value, i'd have to write A 100 times?

**Comment by maxulyanov** [comment]
Hello!
ng2-inputmask does not currently support regular expressions for masks.
You can create a long mask with a loop.
`let myMask = '';
for(let i = 0; i < 100; i++) {
 myMask += 'A'
}`
