### ISSUE TITLE
Can't change text once it is entered

### ISSUE THREAD

**Issue by adamsiembida** [M-Ulyanov/ng2-inputmask#4]
I'm not sure if this is the intended behavior, but once I finish typing text that matches the mask, I can no longer change it.

For example, if `mask="00"`, I can type `12`, however, once I am done entering `12` I can't change it anymore. If I only type the first digit, I can delete it and type something else, just not once it is completed.

**Comment by maxulyanov** [comment]
This is the standard behavior, the mask specifies the type of characters and limits the long string

**Comment by adamsiembida** [comment]
I don't mean limiting the total number of characters, I mean preventing modification after entering the full string.

For example, if I meant to type (555) 555-5555, but accidentally typed (555) 555-5554, it won't let me change the 4 to a 5.

**Comment by maxulyanov** [comment]
Try again, this should be fixed in the new version
