### ISSUE TITLE
How to change the selected text in the field

### ISSUE THREAD

**Issue by vicabelotelova** [M-Ulyanov/ng2-inputmask#5]
I need it when I select the entered values and immediately write new ones, new values were entered. Now when I highlight the values new are not entered, only after removing the entire value from the field. I have no idea how to fix this

**Comment by maxulyanov** [comment]
Sorry, ng2-inputmask limits the ability to enter characters if the length of the value in the field matches the long mask.
Work with the selection will soon be finalized.
