### ISSUE TITLE
Can't submit form while pressing "ENTER" button

### ISSUE THREAD

**Issue by SonicReal** [M-Ulyanov/ng2-inputmask#9]
` 
public onKeyPress(event): void {
    if(!this.mask) return;
    const key = this.getKey(event);
    if(key === keys.BACKSPACE ||key === keys.LEFT || key === keys.RIGHT) return;

    const cursorPosition = this.getCursorPosition();
    let regexp = this.createRegExp(cursorPosition);

    if(regexp != null && !regexp.test(event.key)  || this.getValue().length >= this.mask.length) {
      event.preventDefault();
    }
  }
`
in this function there is event.preventDefault(), so when i'm trying to submit form, it stops there. May be its better to catch this key and prevent from preventing or to add ENTER key to keys const?

**Comment by maxulyanov** [comment]
Fixed https://github.com/M-Ulyanov/ng2-inputmask/pull/10
